config/routes.rb
Excedent::Application.routes.draw do
  resources :offers
  resources :quotes

  root :to => "offers#index"

end

app/models/offer.rb
# valid pricing_types:
# 'horas', 'unidades', 'dias'
#
class Offer < ActiveRecord::Base

  named_scope :smart_find, lambda { |q| { 
    :conditions => " to_tsvector('english', title) @@ to_tsquery('english', '#{q}') "
  } }

  has_many :quotes

  def initialize(attributes = nil)
    attributes ||= {}
    attributes[:starts_at] ||= DateTime.now.strftime("%m-%d-%Y")
    attributes[:ends_at]   ||= DateTime.now.strftime("%m-%d-%Y")
    super
  end



  def self.pricing_types
    ['unidades','horas']
  end

  def self.offer_types
    ['ofrece','busca']
  end

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :offer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # GET /offers
  # GET /offers.xml
  def index
    if params[:q]
      @offers = Offer.smart_find(params[:q])
    else
      @offers = Offer.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.xml
  def show
    @offer = Offer.find(params[:id])
    @quotes = @offer.quotes
    @quote = Quote.new(:offer_id=> @offer.id)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @offer }
    end
  end

  # GET /offers/new
  # GET /offers/new.xml
  def new
    @offer = Offer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
  end

  # POST /offers
  # POST /offers.xml
  def create
    @offer = Offer.new(params[:offer])

    respond_to do |format|
      if @offer.save
        format.html { redirect_to(@offer, :notice => 'Offer was successfully created.') }
        format.xml  { render :xml => @offer, :status => :created, :location => @offer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @offer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.xml
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to(@offer, :notice => 'Offer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @offer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.xml
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to(offers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  # POST /offers
  # POST /offers.xml
  def create
    @quote = Quote.new(params[:quote])

    respond_to do |format|
      if @quote.save
        format.html { redirect_to(:controller=> :offers, :action=>:show, :id=> @quote.offer_id, :notice => 'Cotizacion enviada') }
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_sidebar.html.erb
<div class="block">
  <h3>Buscar</h3>
  <div class="content">
    <h2 class="title"></h2>
    <div class="inner">
      <form action="/offers" method="get" class="search-box form">
        <div class="group">
          <%=text_field_tag 'q', params[:q], :class=>"text_field" %>
          <div class="subgroup">
            <%= select_tag 'type', options_for_select(['Buscadores', 'Oferentes']) %>
            <button class="button" type="submit"> Buscar </button>
            <div class='clear'></div>
          </div>
      </form>
    </div>
  </div>
</div>

<div class="block notice">
  <h4>Notice Title</h4>
  <p>Morbi posuere urna vitae nunc. Curabitur ultrices, lorem ac aliquam blandit, lectus eros hendrerit eros, at eleifend libero ipsum hendrerit urna. Suspendisse viverra. Morbi ut magna. Praesent id ipsum. Sed feugiat ipsum ut felis. Fusce vitae nibh sed risus commodo pulvinar. Duis ut dolor. Cras ac erat pulvinar tortor porta sodales. Aenean tempor venenatis dolor.</p>
</div>
<div class="block">
  <div class="sidebar-block">
    <h4>Sidebar Inner block Title</h4>
    <p>Morbi posuere urna vitae nunc. Curabitur ultrices, lorem ac <a href="#">aliquam blandit</a>, lectus eros hendrerit eros, at eleifend libero ipsum hendrerit urna. Suspendisse viverra. Morbi ut magna. Praesent id ipsum. Sed feugiat ipsum ut felis. Fusce vitae nibh sed risus commodo pulvinar. Duis ut dolor. Cras ac erat pulvinar tortor porta sodales. Aenean tempor venenatis dolor.</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xednt</title>
  <%= stylesheet_link_tag "web-app-theme/base",'smoothness/jquery-ui-1.8.13.custom.css', "web-app-theme/themes/warehouse/style", "web-app-theme/override",'markitup/style', 'markitup/theme', 'style', :cache => true %>

  <%= javascript_include_tag :defaults, 'jquery-1.6.1.min.js', 'jquery-ui-1.8.13.custom.min.js','jquery.markitup', 'markitup_settings', :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1>
        <%= image_tag 'logo.png', :id =>'xednt_logo' %> 
        <a href="/">Xcdnt</a>
      </h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><a href="#"><%= t("web-app-theme.profile", :default => "Perfil") %></a></li>
          <li><a href="#"><%= t("web-app-theme.settings", :default => "Preferencias") %></a></li>
          <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Desconectar") %></a></li>
        </ul>
      </div>

      <div id="main-navigation">
        <ul class="wat-cf">
          <li class="first"><a href="#block-text">Buscadores</a></li>
          <li class="active"><a href="#block-text">Oferentes</a></li>
          <li><a href="#block-signup">Comunidad</a></li>
          <li><a href="/offers/new">Crear</a></li>
        </ul>
      </div>

    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <div id="content-holder">
          <%= yield %>
        </div>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Xcdnt.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= render 'layouts/sidebar' %> 
      </div>
    </div>    
  </div>
</body>
</html>

app/views/offers/_form.html.erb
<%= form_for(@offer, :html => { :class=>'form' }) do |f| %>

<% if @offer.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

  <ul>
    <% @offer.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="group">
  <%= f.label 'Se', :class=> 'label' %>
  <%= f.select :offer_type, Offer.offer_types.map {|t| t.humanize} %>
</div>

<div class="group">
  <%= f.label 'Nombre', :class=> 'label' %>
  <%= f.text_field :title, :class=> 'text_field' %>
</div>
<div class="group">
  <%= f.label 'Descripcion', :class=> 'label' %>
  <%= f.text_area :description, :class => 'markitup text_area', :rows=>'10',:cols=>'80' %>
</div>

<div class="group price">
  <%= f.label 'Cantidad', :class=> 'label' %>
  <%= f.text_field :price, :class=> 'text_field' %>
  <%= f.select :pricing_type, Offer.pricing_types.map {|t| t.humanize} %>
</div>
<div class="group">
</div>

<div class="group">
  <%= f.label 'Desde', :class=> 'label' %>
  <%= f.text_field :starts_at, :class=> 'datepicker' %>
</div>
<div class="group">
  <%= f.label 'Hasta', :class=> 'label' %>
  <%= f.text_field :ends_at, :class=> 'datepicker' %>
</div>


<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_submit_tag 'web-app-theme/icons/tick.png' %> Guardar
  </button>
  <a href="#header" class="button">
    <%= image_submit_tag 'web-app-theme/icons/cross.png' %> Cancelar
  </a>
</div>
<% end %>

app/views/offers/_quote_form.html.erb
<%= form_for(@quote,:url=>{:controller=>:quotes}, :html => { :class=>'form' }) do |f| %>
<div class="group">
  <%= f.label 'Descripcion', :class=> 'label' %>
  <%= f.text_area :description, :class => 'markitup text_area', :rows=>'10',:cols=>'80' %>
  <%= f.hidden_field :offer_id %>
</div>
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_submit_tag 'web-app-theme/icons/tick.png' %> Enviar
  </button>
  <a href="#header" class="button">
    <%= image_submit_tag 'web-app-theme/icons/cross.png' %> Cancelar
  </a>
</div>
<% end%>

app/views/offers/_quotes.html.erb
<% if @quotes && @quotes.size > 0 %>
<div class="block" id="block-lists">
  <div class="content">
    <div class="inner">
      <ul class="list offers">
        <% @quotes.each do |quote| %>
        <li>
        <div class="left">
          <a href="#"><img class="avatar" src="/images/profilemissing.png" alt="avatar"></a>
          <div class="price">
          </div>
        </div>
        <div class="item">
          <p id="description"><%= markdown quote.description %></p>
        </div>
        </li>
        <% end %>
        <div class="clear"></div>
      </ul>
    </div>
  </div>
</div>
<% end %> 

<br />

<div class="block" id="block-forms-2">
  <div class="content">
    <h2 class="title">Cotizar</h2>
    <div class="inner">
      <%= render 'quote_form' %>
    </div>
  </div>
</div>

app/views/offers/edit.html.erb
<div class="block" id="block-forms-2">
  <div class="content">
    <h2 class="title">Editar oferta</h2>
    <div class="inner">
      <%= render 'form' %>
    </div>
  </div>
</div>

<%= link_to 'Destroy', @offer, :confirm => 'Are you sure?', :method => :delete %>
<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h1>Listado de ofertas</h1>

<div class="offers">
</div>

<div class="block" id="block-lists">
  <div class="content">
    <div class="inner">
      <ul class="list offers">
        <% @offers.each do |offer| %>
          <li>
            <div class="left">
              <a href="#"><img class="avatar" src="/images/profilemissing.png" alt="avatar"></a>
              <div class="price">
                <%= pluralize offer.price, offer.pricing_type %> 
              </div>
            </div>
            <div class="item">
              <h3> Se <%= offer.offer_type %>: <%= link_to offer.title, offer %> </h3>
              <p id="description"><%= markdown offer.description %></p>
            </div>
          </li>
        <% end %>
        <div class="clear"></div>
      </ul>
    </div>
  </div>
</div>

<br />

app/views/offers/new.html.erb
<div class="block" id="block-forms-2">
  <div class="content">
    <h2 class="title">Crear Oferta</h2>
    <div class="inner">
      <%= render 'form' %>
    </div>
  </div>
</div>

<%= link_to 'Volver', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Se <%= @offer.offer_type %>: <%= link_to @offer.title, edit_offer_path(@offer) %> </h1>

<div class="flash">
  <div class="message error">
    <p> <%= pluralize @offer.price, @offer.pricing_type %> </p>
  </div>
</div>


<p> <%= markdown @offer.description %> </p>


<div class="quotes">
  <%= render 'quotes' if @offer.offer_type.underscore =='ofrece' %>
</div>